import SwiftUI

/// GENERATED from the colors.toml of every theme Omarchy ships, ported
/// from `android/.../ui/theme/OmarchyThemes.kt`. Regenerate rather than
/// hand-edit: hairlines, bevels, chip borders and meter cells are folded
/// from ground toward ink at fixed ratios there, and onAccent follows the
/// accent's own luminance. Keys are sorted the way settings lists them.
public enum OmarchyPalettes {
    public static let palettes: [String: CliampPalette] = [
        "catppuccin": CliampPalette(
            dark: true,
            canvas: Color(argb: 0xFF101019),
            ground: Color(argb: 0xFF1E1E2E),
            groundScope: Color(argb: 0xFF161622),
            groundLock: Color(argb: 0xFF101019),
            panel: Color(argb: 0xFF313244),
            panelRaised: Color(argb: 0xFF292A3B),
            hairline: Color(argb: 0xFF313244),
            hairlineRegion: Color(argb: 0xFF3E3F52),
            frameBorder: Color(argb: 0xFF525569),
            ink: Color(argb: 0xFFCDD6F4),
            inkBright: Color(argb: 0xFFCDD6F4),
            inkSecondary: Color(argb: 0xFFABAFC7),
            inkTertiary: Color(argb: 0xFFA1A4BC),
            inkFaint: Color(argb: 0xFF979AAF),
            accent: Color(argb: 0xFF89B4FA),
            accentBright: Color(argb: 0xFFBAD3FC),
            accentBevel: Color(argb: 0xFF4588F7),
            onAccent: Color(argb: 0xFF101019),
            accentWash: Color(argb: 0xFF2F364F),
            amber: Color(argb: 0xFFF6B6AB),
            destructive: Color(argb: 0xFFF38BA8),
            destructiveInk: Color(argb: 0xFFF38BA8),
            keyFace: Color(argb: 0xFF313244),
            keyBorder: Color(argb: 0xFF484A5E),
            keyBevel: Color(argb: 0xFF101019),
            chipBorder: Color(argb: 0xFF3F4154),
            track: Color(argb: 0xFF383A4C),
            unlit: Color(argb: 0xFF2F364F),
            peak: Color(argb: 0xFFCDD6F4),
            artA: Color(argb: 0xFF2A2B3C),
            artB: Color(argb: 0xFF242435),
            artBorder: Color(argb: 0xFF3F4154)
        ),
        "catppuccin-latte": CliampPalette(
            dark: false,
            canvas: Color(argb: 0xFFD7D8DC),
            ground: Color(argb: 0xFFEFF1F5),
            groundScope: Color(argb: 0xFFE3E4E8),
            groundLock: Color(argb: 0xFFD7D8DC),
            panel: Color(argb: 0xFFDCE0E8),
            panelRaised: Color(argb: 0xFFE4E7ED),
            hairline: Color(argb: 0xFFDDDFE6),
            hairlineRegion: Color(argb: 0xFFD2D4DC),
            frameBorder: Color(argb: 0xFFBEC0CB),
            ink: Color(argb: 0xFF4C4F69),
            inkBright: Color(argb: 0xFF4C4F69),
            inkSecondary: Color(argb: 0xFF535765),
            inkTertiary: Color(argb: 0xFF595D69),
            inkFaint: Color(argb: 0xFF60636C),
            accent: Color(argb: 0xFF0C57E5),
            accentBright: Color(argb: 0xFF0A52E0),
            accentBevel: Color(argb: 0xFF0947C3),
            onAccent: Color(argb: 0xFF4C4F69),
            accentWash: Color(argb: 0xFFCEDBF5),
            amber: Color(argb: 0xFFB93003),
            destructive: Color(argb: 0xFFD20F39),
            destructiveInk: Color(argb: 0xFFC80031),
            keyFace: Color(argb: 0xFFEFF1F5),
            keyBorder: Color(argb: 0xFFC8CAD3),
            keyBevel: Color(argb: 0xFFDADCE3),
            chipBorder: Color(argb: 0xFFD0D2DA),
            track: Color(argb: 0xFFD7D9E0),
            unlit: Color(argb: 0xFFCEDBF5),
            peak: Color(argb: 0xFF4C4F69),
            artA: Color(argb: 0xFFE4E6EB),
            artB: Color(argb: 0xFFE9EBF0),
            artBorder: Color(argb: 0xFFD0D2DA)
        ),
        "ethereal": CliampPalette(
            dark: true,
            canvas: Color(argb: 0xFF030610),
            ground: Color(argb: 0xFF060B1E),
            groundScope: Color(argb: 0xFF040816),
            groundLock: Color(argb: 0xFF030610),
            panel: Color(argb: 0xFF131A3A),
            panelRaised: Color(argb: 0xFF0E142F),
            hairline: Color(argb: 0xFF21202E),
            hairlineRegion: Color(argb: 0xFF332E38),
            frameBorder: Color(argb: 0xFF514649),
            ink: Color(argb: 0xFFFFCEAD),
            inkBright: Color(argb: 0xFFFFCEAD),
            inkSecondary: Color(argb: 0xFF8697D2),
            inkTertiary: Color(argb: 0xFF7B8CC6),
            inkFaint: Color(argb: 0xFF7582B2),
            accent: Color(argb: 0xFF7D82D9),
            accentBright: Color(argb: 0xFFA4A8E5),
            accentBevel: Color(argb: 0xFF464DC9),
            onAccent: Color(argb: 0xFF3D1900),
            accentWash: Color(argb: 0xFF191E3C),
            amber: Color(argb: 0xFFEB8B54),
            destructive: Color(argb: 0xFFED5B5A),
            destructiveInk: Color(argb: 0xFFFAAAA9),
            keyFace: Color(argb: 0xFF131A3A),
            keyBorder: Color(argb: 0xFF423A40),
            keyBevel: Color(argb: 0xFF030610),
            chipBorder: Color(argb: 0xFF353039),
            track: Color(argb: 0xFF2B2833),
            unlit: Color(argb: 0xFF191E3C),
            peak: Color(argb: 0xFFFFCEAD),
            artA: Color(argb: 0xFF171928),
            artB: Color(argb: 0xFF0F1223),
            artBorder: Color(argb: 0xFF353039)
        ),
        "everforest": CliampPalette(
            dark: true,
            canvas: Color(argb: 0xFF181D20),
            ground: Color(argb: 0xFF2D353B),
            groundScope: Color(argb: 0xFF21272C),
            groundLock: Color(argb: 0xFF181D20),
            panel: Color(argb: 0xFF343F44),
            panelRaised: Color(argb: 0xFF313B40),
            hairline: Color(argb: 0xFF3F4547),
            hairlineRegion: Color(argb: 0xFF4B4F4F),
            frameBorder: Color(argb: 0xFF5F605C),
            ink: Color(argb: 0xFFD3C6AA),
            inkBright: Color(argb: 0xFFD3C6AA),
            inkSecondary: Color(argb: 0xFFB4BEC5),
            inkTertiary: Color(argb: 0xFFA8B4BB),
            inkFaint: Color(argb: 0xFF9EAAB0),
            accent: Color(argb: 0xFF7FBBB3),
            accentBright: Color(argb: 0xFFA0CDC7),
            accentBevel: Color(argb: 0xFF549E95),
            onAccent: Color(argb: 0xFF181D20),
            accentWash: Color(argb: 0xFF3A4A4E),
            amber: Color(argb: 0xFFE09D7F),
            destructive: Color(argb: 0xFFE67E80),
            destructiveInk: Color(argb: 0xFFF38A8B),
            keyFace: Color(argb: 0xFF343F44),
            keyBorder: Color(argb: 0xFF555856),
            keyBevel: Color(argb: 0xFF181D20),
            chipBorder: Color(argb: 0xFF4D5150),
            track: Color(argb: 0xFF464B4C),
            unlit: Color(argb: 0xFF3A4A4E),
            peak: Color(argb: 0xFFD3C6AA),
            artA: Color(argb: 0xFF393F43),
            artB: Color(argb: 0xFF333A3F),
            artBorder: Color(argb: 0xFF4D5150)
        ),
        "flexoki-light": CliampPalette(
            dark: false,
            canvas: Color(argb: 0xFFE5E2D8),
            ground: Color(argb: 0xFFFFFCF0),
            groundScope: Color(argb: 0xFFF2EFE4),
            groundLock: Color(argb: 0xFFE5E2D8),
            panel: Color(argb: 0xFFE6E4D9),
            panelRaised: Color(argb: 0xFFF0EEE2),
            hairline: Color(argb: 0xFFE5E2D7),
            hairlineRegion: Color(argb: 0xFFD4D1C8),
            frameBorder: Color(argb: 0xFFB7B5AC),
            ink: Color(argb: 0xFF100F0F),
            inkBright: Color(argb: 0xFF100F0F),
            inkSecondary: Color(argb: 0xFF54524D),
            inkTertiary: Color(argb: 0xFF5E5C54),
            inkFaint: Color(argb: 0xFF67665D),
            accent: Color(argb: 0xFF205EA6),
            accentBright: Color(argb: 0xFF194B84),
            accentBevel: Color(argb: 0xFF143C6A),
            onAccent: Color(argb: 0xFF100F0F),
            accentWash: Color(argb: 0xFFDBE3E4),
            amber: Color(argb: 0xFFA24E00),
            destructive: Color(argb: 0xFFD14D41),
            destructiveInk: Color(argb: 0xFFB9362D),
            keyFace: Color(argb: 0xFFFFFCF0),
            keyBorder: Color(argb: 0xFFC6C3BA),
            keyBevel: Color(argb: 0xFFE0DDD3),
            chipBorder: Color(argb: 0xFFD2CFC5),
            track: Color(argb: 0xFFDBD8CE),
            unlit: Color(argb: 0xFFDBE3E4),
            peak: Color(argb: 0xFF100F0F),
            artA: Color(argb: 0xFFEEEBE0),
            artB: Color(argb: 0xFFF7F4E8),
            artBorder: Color(argb: 0xFFD2CFC5)
        ),
        "gruvbox": CliampPalette(
            dark: true,
            canvas: Color(argb: 0xFF161616),
            ground: Color(argb: 0xFF282828),
            groundScope: Color(argb: 0xFF1E1E1E),
            groundLock: Color(argb: 0xFF161616),
            panel: Color(argb: 0xFF3C3836),
            panelRaised: Color(argb: 0xFF343230),
            hairline: Color(argb: 0xFF3B3834),
            hairlineRegion: Color(argb: 0xFF47433C),
            frameBorder: Color(argb: 0xFF5C554A),
            ink: Color(argb: 0xFFD4BE98),
            inkBright: Color(argb: 0xFFD4BE98),
            inkSecondary: Color(argb: 0xFFC2B4A8),
            inkTertiary: Color(argb: 0xFFB5AAA1),
            inkFaint: Color(argb: 0xFFA7A19B),
            accent: Color(argb: 0xFF7DAEA3),
            accentBright: Color(argb: 0xFF9CC2B9),
            accentBevel: Color(argb: 0xFF578C80),
            onAccent: Color(argb: 0xFF4A3815),
            accentWash: Color(argb: 0xFF363D3C),
            amber: Color(argb: 0xFFE58B5F),
            destructive: Color(argb: 0xFFEA6962),
            destructiveInk: Color(argb: 0xFFFD7A71),
            keyFace: Color(argb: 0xFF3C3836),
            keyBorder: Color(argb: 0xFF514C43),
            keyBevel: Color(argb: 0xFF161616),
            chipBorder: Color(argb: 0xFF49443D),
            track: Color(argb: 0xFF423E39),
            unlit: Color(argb: 0xFF363D3C),
            peak: Color(argb: 0xFFD4BE98),
            artA: Color(argb: 0xFF343230),
            artB: Color(argb: 0xFF2E2D2C),
            artBorder: Color(argb: 0xFF49443D)
        ),
        "hackerman": CliampPalette(
            dark: true,
            canvas: Color(argb: 0xFF06060C),
            ground: Color(argb: 0xFF0B0C16),
            groundScope: Color(argb: 0xFF080910),
            groundLock: Color(argb: 0xFF06060C),
            panel: Color(argb: 0xFF151828),
            panelRaised: Color(argb: 0xFF111321),
            hairline: Color(argb: 0xFF222630),
            hairlineRegion: Color(argb: 0xFF313640),
            frameBorder: Color(argb: 0xFF4A525C),
            ink: Color(argb: 0xFFDDF7FF),
            inkBright: Color(argb: 0xFFDDF7FF),
            inkSecondary: Color(argb: 0xFF8F93BC),
            inkTertiary: Color(argb: 0xFF828BAC),
            inkFaint: Color(argb: 0xFF79819B),
            accent: Color(argb: 0xFF82FB9C),
            accentBright: Color(argb: 0xFFB3FDC3),
            accentBevel: Color(argb: 0xFF3DF965),
            onAccent: Color(argb: 0xFF06060C),
            accentWash: Color(argb: 0xFF1E322B),
            amber: Color(argb: 0xFF50F7A3),
            destructive: Color(argb: 0xFF50F872),
            destructiveInk: Color(argb: 0xFF85FF9D),
            keyFace: Color(argb: 0xFF151828),
            keyBorder: Color(argb: 0xFF3D444E),
            keyBevel: Color(argb: 0xFF06060C),
            chipBorder: Color(argb: 0xFF333942),
            track: Color(argb: 0xFF2A2F39),
            unlit: Color(argb: 0xFF1E322B),
            peak: Color(argb: 0xFFDDF7FF),
            artA: Color(argb: 0xFF1A1C26),
            artB: Color(argb: 0xFF12141E),
            artBorder: Color(argb: 0xFF333942)
        ),
        "kanagawa": CliampPalette(
            dark: true,
            canvas: Color(argb: 0xFF111116),
            ground: Color(argb: 0xFF1F1F28),
            groundScope: Color(argb: 0xFF17171E),
            groundLock: Color(argb: 0xFF111116),
            panel: Color(argb: 0xFF223249),
            panelRaised: Color(argb: 0xFF212A3C),
            hairline: Color(argb: 0xFF343338),
            hairlineRegion: Color(argb: 0xFF414042),
            frameBorder: Color(argb: 0xFF585654),
            ink: Color(argb: 0xFFDCD7BA),
            inkBright: Color(argb: 0xFFDCD7BA),
            inkSecondary: Color(argb: 0xFFB0AFA6),
            inkTertiary: Color(argb: 0xFFA0A1BD),
            inkFaint: Color(argb: 0xFF9697AE),
            accent: Color(argb: 0xFFDCD7BA),
            accentBright: Color(argb: 0xFFEDEBDC),
            accentBevel: Color(argb: 0xFFC4BC8B),
            onAccent: Color(argb: 0xFF111116),
            accentWash: Color(argb: 0xFF3D3C3F),
            amber: Color(argb: 0xFFD5846A),
            destructive: Color(argb: 0xFFC34043),
            destructiveInk: Color(argb: 0xFFFF6E61),
            keyFace: Color(argb: 0xFF223249),
            keyBorder: Color(argb: 0xFF4C4B4B),
            keyBevel: Color(argb: 0xFF111116),
            chipBorder: Color(argb: 0xFF434244),
            track: Color(argb: 0xFF3B3B3E),
            unlit: Color(argb: 0xFF3D3C3F),
            peak: Color(argb: 0xFFDCD7BA),
            artA: Color(argb: 0xFF2C2C32),
            artB: Color(argb: 0xFF26252D),
            artBorder: Color(argb: 0xFF434244)
        ),
        "last-horizon": CliampPalette(
            dark: true,
            canvas: Color(argb: 0xFF060606),
            ground: Color(argb: 0xFF0C0B0C),
            groundScope: Color(argb: 0xFF090809),
            groundLock: Color(argb: 0xFF060606),
            panel: Color(argb: 0xFF0C0B0C),
            panelRaised: Color(argb: 0xFF0C0B0C),
            hairline: Color(argb: 0xFF262626),
            hairlineRegion: Color(argb: 0xFF373637),
            frameBorder: Color(argb: 0xFF535354),
            ink: Color(argb: 0xFFFAFCFB),
            inkBright: Color(argb: 0xFFE2DDDC),
            inkSecondary: Color(argb: 0xFF968B8E),
            inkTertiary: Color(argb: 0xFF8C8184),
            inkFaint: Color(argb: 0xFF7E787A),
            accent: Color(argb: 0xFFB59790),
            accentBright: Color(argb: 0xFFC9B4AF),
            accentBevel: Color(argb: 0xFF986F65),
            onAccent: Color(argb: 0xFF383434),
            accentWash: Color(argb: 0xFF272121),
            amber: Color(argb: 0xFF82758A),
            destructive: Color(argb: 0xFFC38B7B),
            destructiveInk: Color(argb: 0xFFC38B7B),
            keyFace: Color(argb: 0xFF0C0B0C),
            keyBorder: Color(argb: 0xFF454545),
            keyBevel: Color(argb: 0xFF060606),
            chipBorder: Color(argb: 0xFF393939),
            track: Color(argb: 0xFF302F30),
            unlit: Color(argb: 0xFF272121),
            peak: Color(argb: 0xFFE2DDDC),
            artA: Color(argb: 0xFF1D1C1D),
            artB: Color(argb: 0xFF141314),
            artBorder: Color(argb: 0xFF393939)
        ),
        "lumon": CliampPalette(
            dark: true,
            canvas: Color(argb: 0xFF0B1216),
            ground: Color(argb: 0xFF16242D),
            groundScope: Color(argb: 0xFF101B21),
            groundLock: Color(argb: 0xFF0B1216),
            panel: Color(argb: 0xFF1B2D40),
            panelRaised: Color(argb: 0xFF192938),
            hairline: Color(argb: 0xFF2B3942),
            hairlineRegion: Color(argb: 0xFF394650),
            frameBorder: Color(argb: 0xFF505D67),
            ink: Color(argb: 0xFFD6E2EE),
            inkBright: Color(argb: 0xFFF2FCFF),
            inkSecondary: Color(argb: 0xFF74AEDA),
            inkTertiary: Color(argb: 0xFF859FBB),
            inkFaint: Color(argb: 0xFF7E95AB),
            accent: Color(argb: 0xFF8BC9EB),
            accentBright: Color(argb: 0xFFB6DDF2),
            accentBevel: Color(argb: 0xFF4EADE0),
            onAccent: Color(argb: 0xFF0B1216),
            accentWash: Color(argb: 0xFF293E4B),
            amber: Color(argb: 0xFF8BC9EB),
            destructive: Color(argb: 0xFF4D86B0),
            destructiveInk: Color(argb: 0xFF73A6CB),
            keyFace: Color(argb: 0xFF1B2D40),
            keyBorder: Color(argb: 0xFF44525B),
            keyBevel: Color(argb: 0xFF0B1216),
            chipBorder: Color(argb: 0xFF3A4852),
            track: Color(argb: 0xFF33404A),
            unlit: Color(argb: 0xFF293E4B),
            peak: Color(argb: 0xFFF2FCFF),
            artA: Color(argb: 0xFF23313B),
            artB: Color(argb: 0xFF1D2B34),
            artBorder: Color(argb: 0xFF3A4852)
        ),
        "lupine": CliampPalette(
            dark: false,
            canvas: Color(argb: 0xFFDEDEDE),
            ground: Color(argb: 0xFFFAFAFA),
            groundScope: Color(argb: 0xFFECECEC),
            groundLock: Color(argb: 0xFFDEDEDE),
            panel: Color(argb: 0xFFF5F5F5),
            panelRaised: Color(argb: 0xFFF7F7F7),
            hairline: Color(argb: 0xFFE2E2E2),
            hairlineRegion: Color(argb: 0xFFD3D3D3),
            frameBorder: Color(argb: 0xFFB9B9B9),
            ink: Color(argb: 0xFF212121),
            inkBright: Color(argb: 0xFF000000),
            inkSecondary: Color(argb: 0xFF575757),
            inkTertiary: Color(argb: 0xFF616161),
            inkFaint: Color(argb: 0xFF6B6A6A),
            accent: Color(argb: 0xFF2E60E6),
            accentBright: Color(argb: 0xFF164CDE),
            accentBevel: Color(argb: 0xFF1342C3),
            onAccent: Color(argb: 0xFF000000),
            accentWash: Color(argb: 0xFFDAE2F8),
            amber: Color(argb: 0xFF0067D6),
            destructive: Color(argb: 0xFFC900C4),
            destructiveInk: Color(argb: 0xFFBD00C0),
            keyFace: Color(argb: 0xFFFAFAFA),
            keyBorder: Color(argb: 0xFFC6C6C6),
            keyBevel: Color(argb: 0xFFDEDEDE),
            chipBorder: Color(argb: 0xFFD1D1D1),
            track: Color(argb: 0xFFD9D9D9),
            unlit: Color(argb: 0xFFDAE2F8),
            peak: Color(argb: 0xFF000000),
            artA: Color(argb: 0xFFEBEBEB),
            artB: Color(argb: 0xFFF2F2F2),
            artBorder: Color(argb: 0xFFD1D1D1)
        ),
        "matte-black": CliampPalette(
            dark: true,
            canvas: Color(argb: 0xFF090909),
            ground: Color(argb: 0xFF121212),
            groundScope: Color(argb: 0xFF0D0D0D),
            groundLock: Color(argb: 0xFF090909),
            panel: Color(argb: 0xFF1E1E1E),
            panelRaised: Color(argb: 0xFF191919),
            hairline: Color(argb: 0xFF252525),
            hairlineRegion: Color(argb: 0xFF313131),
            frameBorder: Color(argb: 0xFF464646),
            ink: Color(argb: 0xFFBEBEBE),
            inkBright: Color(argb: 0xFFBEBEBE),
            inkSecondary: Color(argb: 0xFF9B9B9B),
            inkTertiary: Color(argb: 0xFF909090),
            inkFaint: Color(argb: 0xFF868585),
            accent: Color(argb: 0xFFE68E0D),
            accentBright: Color(argb: 0xFFF3A533),
            accentBevel: Color(argb: 0xFFA26409),
            onAccent: Color(argb: 0xFF393939),
            accentWash: Color(argb: 0xFF342611),
            amber: Color(argb: 0xFFE25754),
            destructive: Color(argb: 0xFFD35F5F),
            destructiveInk: Color(argb: 0xFFE95046),
            keyFace: Color(argb: 0xFF1E1E1E),
            keyBorder: Color(argb: 0xFF3B3B3B),
            keyBevel: Color(argb: 0xFF090909),
            chipBorder: Color(argb: 0xFF333333),
            track: Color(argb: 0xFF2C2C2C),
            unlit: Color(argb: 0xFF342611),
            peak: Color(argb: 0xFFBEBEBE),
            artA: Color(argb: 0xFF1E1E1E),
            artB: Color(argb: 0xFF181818),
            artBorder: Color(argb: 0xFF333333)
        ),
        "miasma": CliampPalette(
            dark: true,
            canvas: Color(argb: 0xFF121212),
            ground: Color(argb: 0xFF222222),
            groundScope: Color(argb: 0xFF191919),
            groundLock: Color(argb: 0xFF121212),
            panel: Color(argb: 0xFF2C2C2C),
            panelRaised: Color(argb: 0xFF282828),
            hairline: Color(argb: 0xFF343432),
            hairlineRegion: Color(argb: 0xFF3F3F3C),
            frameBorder: Color(argb: 0xFF52524D),
            ink: Color(argb: 0xFFC2C2B0),
            inkBright: Color(argb: 0xFFC2C2B0),
            inkSecondary: Color(argb: 0xFFA8A8A8),
            inkTertiary: Color(argb: 0xFF9D9D9D),
            inkFaint: Color(argb: 0xFF939392),
            accent: Color(argb: 0xFF8E9860),
            accentBright: Color(argb: 0xFF96A25E),
            accentBevel: Color(argb: 0xFF4E5531),
            onAccent: Color(argb: 0xFF2D2D1E),
            accentWash: Color(argb: 0xFF303129),
            amber: Color(argb: 0xFFB78A68),
            destructive: Color(argb: 0xFF685742),
            destructiveInk: Color(argb: 0xFFA29079),
            keyFace: Color(argb: 0xFF2C2C2C),
            keyBorder: Color(argb: 0xFF484844),
            keyBevel: Color(argb: 0xFF121212),
            chipBorder: Color(argb: 0xFF40403D),
            track: Color(argb: 0xFF3A3A37),
            unlit: Color(argb: 0xFF303129),
            peak: Color(argb: 0xFFC2C2B0),
            artA: Color(argb: 0xFF2D2D2C),
            artB: Color(argb: 0xFF282827),
            artBorder: Color(argb: 0xFF40403D)
        ),
        "nord": CliampPalette(
            dark: true,
            canvas: Color(argb: 0xFF191C23),
            ground: Color(argb: 0xFF2E3440),
            groundScope: Color(argb: 0xFF222730),
            groundLock: Color(argb: 0xFF191C23),
            panel: Color(argb: 0xFF3B4252),
            panelRaised: Color(argb: 0xFF363C4B),
            hairline: Color(argb: 0xFF414753),
            hairlineRegion: Color(argb: 0xFF4D535E),
            frameBorder: Color(argb: 0xFF616773),
            ink: Color(argb: 0xFFD8DEE9),
            inkBright: Color(argb: 0xFFD8DEE9),
            inkSecondary: Color(argb: 0xFFBAC5D7),
            inkTertiary: Color(argb: 0xFFAEBAD1),
            inkFaint: Color(argb: 0xFFA5AFC2),
            accent: Color(argb: 0xFF91B2D2),
            accentBright: Color(argb: 0xFFA3BAD2),
            accentBevel: Color(argb: 0xFF537DA8),
            onAccent: Color(argb: 0xFF3E424B),
            accentWash: Color(argb: 0xFF3B4555),
            amber: Color(argb: 0xFFDFA083),
            destructive: Color(argb: 0xFFBF616A),
            destructiveInk: Color(argb: 0xFFF59299),
            keyFace: Color(argb: 0xFF3B4252),
            keyBorder: Color(argb: 0xFF575D69),
            keyBevel: Color(argb: 0xFF191C23),
            chipBorder: Color(argb: 0xFF4E5460),
            track: Color(argb: 0xFF484E59),
            unlit: Color(argb: 0xFF3B4555),
            peak: Color(argb: 0xFFD8DEE9),
            artA: Color(argb: 0xFF3A404C),
            artB: Color(argb: 0xFF343A46),
            artBorder: Color(argb: 0xFF4E5460)
        ),
        "osaka-jade": CliampPalette(
            dark: true,
            canvas: Color(argb: 0xFF090F0D),
            ground: Color(argb: 0xFF111C18),
            groundScope: Color(argb: 0xFF0C1512),
            groundLock: Color(argb: 0xFF090F0D),
            panel: Color(argb: 0xFF23372B),
            panelRaised: Color(argb: 0xFF1C2C23),
            hairline: Color(argb: 0xFF242E26),
            hairlineRegion: Color(argb: 0xFF313A2F),
            frameBorder: Color(argb: 0xFF464E3E),
            ink: Color(argb: 0xFFC1C497),
            inkBright: Color(argb: 0xFFF7E8B2),
            inkSecondary: Color(argb: 0xFF85BCAC),
            inkTertiary: Color(argb: 0xFF94AA9C),
            inkFaint: Color(argb: 0xFF8C9F94),
            accent: Color(argb: 0xFF63A888),
            accentBright: Color(argb: 0xFF69AE8F),
            accentBevel: Color(argb: 0xFF376650),
            onAccent: Color(argb: 0xFF3F3100),
            accentWash: Color(argb: 0xFF1B2F27),
            amber: Color(argb: 0xFFC19168),
            destructive: Color(argb: 0xFFFF5345),
            destructiveInk: Color(argb: 0xFFDB9F9C),
            keyFace: Color(argb: 0xFF23372B),
            keyBorder: Color(argb: 0xFF3B4436),
            keyBevel: Color(argb: 0xFF090F0D),
            chipBorder: Color(argb: 0xFF323C30),
            track: Color(argb: 0xFF2B352B),
            unlit: Color(argb: 0xFF1B2F27),
            peak: Color(argb: 0xFFF7E8B2),
            artA: Color(argb: 0xFF1D2821),
            artB: Color(argb: 0xFF17221C),
            artBorder: Color(argb: 0xFF323C30)
        ),
        "retro-82": CliampPalette(
            dark: true,
            canvas: Color(argb: 0xFF020C17),
            ground: Color(argb: 0xFF05182E),
            groundScope: Color(argb: 0xFF031222),
            groundLock: Color(argb: 0xFF020C17),
            panel: Color(argb: 0xFF0A2540),
            panelRaised: Color(argb: 0xFF082039),
            hairline: Color(argb: 0xFF202E3C),
            hairlineRegion: Color(argb: 0xFF303B45),
            frameBorder: Color(argb: 0xFF4D5354),
            ink: Color(argb: 0xFFF6DCAC),
            inkBright: Color(argb: 0xFFF6DCAC),
            inkSecondary: Color(argb: 0xFF60AEA9),
            inkTertiary: Color(argb: 0xFF609FAD),
            inkFaint: Color(argb: 0xFF6192A3),
            accent: Color(argb: 0xFFFAA968),
            accentBright: Color(argb: 0xFFFCC599),
            accentBevel: Color(argb: 0xFFF88223),
            onAccent: Color(argb: 0xFF020C17),
            accentWash: Color(argb: 0xFF2C2F37),
            amber: Color(argb: 0xFFFAA968),
            destructive: Color(argb: 0xFFF85525),
            destructiveInk: Color(argb: 0xFFF85525),
            keyFace: Color(argb: 0xFF0A2540),
            keyBorder: Color(argb: 0xFF3F474C),
            keyBevel: Color(argb: 0xFF020C17),
            chipBorder: Color(argb: 0xFF333D46),
            track: Color(argb: 0xFF293541),
            unlit: Color(argb: 0xFF2C2F37),
            peak: Color(argb: 0xFFF6DCAC),
            artA: Color(argb: 0xFF162637),
            artB: Color(argb: 0xFF0D1F32),
            artBorder: Color(argb: 0xFF333D46)
        ),
        "ristretto": CliampPalette(
            dark: true,
            canvas: Color(argb: 0xFF181414),
            ground: Color(argb: 0xFF2C2525),
            groundScope: Color(argb: 0xFF211B1B),
            groundLock: Color(argb: 0xFF181414),
            panel: Color(argb: 0xFF3D2F2A),
            panelRaised: Color(argb: 0xFF362B28),
            hairline: Color(argb: 0xFF403939),
            hairlineRegion: Color(argb: 0xFF4D4546),
            frameBorder: Color(argb: 0xFF645B5C),
            ink: Color(argb: 0xFFE6D9DB),
            inkBright: Color(argb: 0xFFE6D9DB),
            inkSecondary: Color(argb: 0xFFB7ADAE),
            inkTertiary: Color(argb: 0xFFACA2A3),
            inkFaint: Color(argb: 0xFFA29798),
            accent: Color(argb: 0xFFF38D70),
            accentBright: Color(argb: 0xFFF7B39F),
            accentBevel: Color(argb: 0xFFED582E),
            onAccent: Color(argb: 0xFF463B3D),
            accentWash: Color(argb: 0xFF4C3631),
            amber: Color(argb: 0xFFFB9A77),
            destructive: Color(argb: 0xFFFD6883),
            destructiveInk: Color(argb: 0xFFFF8297),
            keyFace: Color(argb: 0xFF3D2F2A),
            keyBorder: Color(argb: 0xFF595051),
            keyBevel: Color(argb: 0xFF181414),
            chipBorder: Color(argb: 0xFF4F4748),
            track: Color(argb: 0xFF484040),
            unlit: Color(argb: 0xFF4C3631),
            peak: Color(argb: 0xFFE6D9DB),
            artA: Color(argb: 0xFF393232),
            artB: Color(argb: 0xFF332B2B),
            artBorder: Color(argb: 0xFF4F4748)
        ),
        "rose-pine": CliampPalette(
            dark: false,
            canvas: Color(argb: 0xFFE1DBD5),
            ground: Color(argb: 0xFFFAF4ED),
            groundScope: Color(argb: 0xFFEDE7E1),
            groundLock: Color(argb: 0xFFE1DBD5),
            panel: Color(argb: 0xFFF2E9E1),
            panelRaised: Color(argb: 0xFFF5EDE6),
            hairline: Color(argb: 0xFFE8E2E0),
            hairlineRegion: Color(argb: 0xFFDDD7D8),
            frameBorder: Color(argb: 0xFFC9C3CA),
            ink: Color(argb: 0xFF575279),
            inkBright: Color(argb: 0xFF575279),
            inkSecondary: Color(argb: 0xFF5F5A6B),
            inkTertiary: Color(argb: 0xFF656264),
            inkFaint: Color(argb: 0xFF6B6767),
            accent: Color(argb: 0xFF32717B),
            accentBright: Color(argb: 0xFF487B85),
            accentBevel: Color(argb: 0xFF3D6971),
            onAccent: Color(argb: 0xFF575279),
            accentWash: Color(argb: 0xFFE0E5E1),
            amber: Color(argb: 0xFF9F542B),
            destructive: Color(argb: 0xFFB4637A),
            destructiveInk: Color(argb: 0xFF9E4F67),
            keyFace: Color(argb: 0xFFFAF4ED),
            keyBorder: Color(argb: 0xFFD3CDD1),
            keyBevel: Color(argb: 0xFFE5DFDE),
            chipBorder: Color(argb: 0xFFDBD5D7),
            track: Color(argb: 0xFFE2DCDC),
            unlit: Color(argb: 0xFFE0E5E1),
            peak: Color(argb: 0xFF575279),
            artA: Color(argb: 0xFFEFE9E5),
            artB: Color(argb: 0xFFF4EEE9),
            artBorder: Color(argb: 0xFFDBD5D7)
        ),
        "solitude": CliampPalette(
            dark: true,
            canvas: Color(argb: 0xFF080A0B),
            ground: Color(argb: 0xFF101315),
            groundScope: Color(argb: 0xFF0C0E10),
            groundLock: Color(argb: 0xFF080A0B),
            panel: Color(argb: 0xFF101315),
            panelRaised: Color(argb: 0xFF101315),
            hairline: Color(argb: 0xFF242729),
            hairlineRegion: Color(argb: 0xFF313436),
            frameBorder: Color(argb: 0xFF484A4C),
            ink: Color(argb: 0xFFCACCCC),
            inkBright: Color(argb: 0xFFA5AEB4),
            inkSecondary: Color(argb: 0xFF8E929A),
            inkTertiary: Color(argb: 0xFF84878F),
            inkFaint: Color(argb: 0xFF7A7D84),
            accent: Color(argb: 0xFF798186),
            accentBright: Color(argb: 0xFF949A9E),
            accentBevel: Color(argb: 0xFF575D60),
            onAccent: Color(argb: 0xFF11181C),
            accentWash: Color(argb: 0xFF212527),
            amber: Color(argb: 0xFFD9DBDC),
            destructive: Color(argb: 0xFF565D60),
            destructiveInk: Color(argb: 0xFFDE6145),
            keyFace: Color(argb: 0xFF101315),
            keyBorder: Color(argb: 0xFF3D3F41),
            keyBevel: Color(argb: 0xFF080A0B),
            chipBorder: Color(argb: 0xFF333638),
            track: Color(argb: 0xFF2C2F30),
            unlit: Color(argb: 0xFF212527),
            peak: Color(argb: 0xFFA5AEB4),
            artA: Color(argb: 0xFF1D2022),
            artB: Color(argb: 0xFF17191B),
            artBorder: Color(argb: 0xFF333638)
        ),
        "tokyo-night": CliampPalette(
            dark: true,
            canvas: Color(argb: 0xFF0E0E14),
            ground: Color(argb: 0xFF1A1B26),
            groundScope: Color(argb: 0xFF13141C),
            groundLock: Color(argb: 0xFF0E0E14),
            panel: Color(argb: 0xFF24283B),
            panelRaised: Color(argb: 0xFF202333),
            hairline: Color(argb: 0xFF2A2C39),
            hairlineRegion: Color(argb: 0xFF343646),
            frameBorder: Color(argb: 0xFF45485B),
            ink: Color(argb: 0xFFA9B1D6),
            inkBright: Color(argb: 0xFFC0CAF5),
            inkSecondary: Color(argb: 0xFF98A3D1),
            inkTertiary: Color(argb: 0xFF9099BD),
            inkFaint: Color(argb: 0xFF888FAC),
            accent: Color(argb: 0xFF7AA2F7),
            accentBright: Color(argb: 0xFFAAC4FA),
            accentBevel: Color(argb: 0xFF3773F3),
            onAccent: Color(argb: 0xFF31385A),
            accentWash: Color(argb: 0xFF293147),
            amber: Color(argb: 0xFFEB927B),
            destructive: Color(argb: 0xFFF7768E),
            destructiveInk: Color(argb: 0xFFFF7A93),
            keyFace: Color(argb: 0xFF24283B),
            keyBorder: Color(argb: 0xFF3C3F50),
            keyBevel: Color(argb: 0xFF0E0E14),
            chipBorder: Color(argb: 0xFF353847),
            track: Color(argb: 0xFF2F3240),
            unlit: Color(argb: 0xFF293147),
            peak: Color(argb: 0xFFC0CAF5),
            artA: Color(argb: 0xFF242632),
            artB: Color(argb: 0xFF1F202C),
            artBorder: Color(argb: 0xFF353847)
        ),
        "vantablack": CliampPalette(
            dark: true,
            canvas: Color(argb: 0xFF070707),
            ground: Color(argb: 0xFF000000),
            groundScope: Color(argb: 0xFF090909),
            groundLock: Color(argb: 0xFF070707),
            panel: Color(argb: 0xFF1A1A1A),
            panelRaised: Color(argb: 0xFF101010),
            hairline: Color(argb: 0xFF1C1C1C),
            hairlineRegion: Color(argb: 0xFF2E2E2E),
            frameBorder: Color(argb: 0xFF4C4C4C),
            ink: Color(argb: 0xFFFFFFFF),
            inkBright: Color(argb: 0xFFFFFFFF),
            inkSecondary: Color(argb: 0xFF979797),
            inkTertiary: Color(argb: 0xFF8C8C8C),
            inkFaint: Color(argb: 0xFF828281),
            accent: Color(argb: 0xFF8D8D8D),
            accentBright: Color(argb: 0xFFA6A6A6),
            accentBevel: Color(argb: 0xFF696969),
            onAccent: Color(argb: 0xFF272626),
            accentWash: Color(argb: 0xFF171717),
            amber: Color(argb: 0xFFB9B9B9),
            destructive: Color(argb: 0xFFA4A4A4),
            destructiveInk: Color(argb: 0xFFA4A4A4),
            keyFace: Color(argb: 0xFF1A1A1A),
            keyBorder: Color(argb: 0xFF3D3D3D),
            keyBevel: Color(argb: 0xFF070707),
            chipBorder: Color(argb: 0xFF303030),
            track: Color(argb: 0xFF262626),
            unlit: Color(argb: 0xFF171717),
            peak: Color(argb: 0xFFFFFFFF),
            artA: Color(argb: 0xFF121212),
            artB: Color(argb: 0xFF090909),
            artBorder: Color(argb: 0xFF303030)
        ),
        "white": CliampPalette(
            dark: false,
            canvas: Color(argb: 0xFFE8E8E8),
            ground: Color(argb: 0xFFFFFFFF),
            groundScope: Color(argb: 0xFFF5F5F5),
            groundLock: Color(argb: 0xFFE8E8E8),
            panel: Color(argb: 0xFFC0C0C0),
            panelRaised: Color(argb: 0xFFD9D9D9),
            hairline: Color(argb: 0xFFE3E3E3),
            hairlineRegion: Color(argb: 0xFFD1D1D1),
            frameBorder: Color(argb: 0xFFB2B2B2),
            ink: Color(argb: 0xFF000000),
            inkBright: Color(argb: 0xFF000000),
            inkSecondary: Color(argb: 0xFF3C3C3C),
            inkTertiary: Color(argb: 0xFF454545),
            inkFaint: Color(argb: 0xFF4F4E4E),
            accent: Color(argb: 0xFF4F4E4E),
            accentBright: Color(argb: 0xFF5A5A5A),
            accentBevel: Color(argb: 0xFF4A4A4A),
            onAccent: Color(argb: 0xFF000000),
            accentWash: Color(argb: 0xFFE8E8E8),
            amber: Color(argb: 0xFF4A4A4A),
            destructive: Color(argb: 0xFF2A2A2A),
            destructiveInk: Color(argb: 0xFF2A2A2A),
            keyFace: Color(argb: 0xFFFFFFFF),
            keyBorder: Color(argb: 0xFFC2C2C2),
            keyBevel: Color(argb: 0xFFDEDEDE),
            chipBorder: Color(argb: 0xFFCFCFCF),
            track: Color(argb: 0xFFD9D9D9),
            unlit: Color(argb: 0xFFE8E8E8),
            peak: Color(argb: 0xFF000000),
            artA: Color(argb: 0xFFEDEDED),
            artB: Color(argb: 0xFFF6F6F6),
            artBorder: Color(argb: 0xFFCFCFCF)
        ),
    ]

    /// Theme keys, alphabetical, as the settings list shows them.
    public static let keys: [String] = palettes.keys.sorted()
}
